version: '3.8'
services:
  app:
    environment:
      - "NEXT_WEBPACK_USE_POLLING=1"
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/src/app
      - /node_modules
      - /.next
      - ./.docker.env.development:/src/app/.env.development:readonly
    ports:
      - "3000:3000"
  mock-server:
    build:
      context: .
      target: mock
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./clean-mock-server.json:/mock-server.json:readonly
