version: '3.8'
services:
  app:
    environment:
      - "NEXT_WEBPACK_USE_POLLING=1"
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: always
    command: yarn dev
    volumes:
      - .:/src/app
      - /src/app/node_modules
      - /src/app/.next
    ports:
      - "3000:3000"
